<?php
/*$img_align = 'left';
if ($this->getData('img_align')) {
	$img_align = $this->getData('img_align');
}
$img_resize_to = '';
if ($this->getData('img_align')) {
	$img_resize_to = $this->getData('img_resize_to');
}*/
$attribute_code = $this->getDataOr('attribute_code', 'manufacturer');
$image_only = $this->getDataOr('image_only', false);
$text_only = $this->getDataOr('text_only', false);
$img_resize_to = $this->getDataOr('img_resize_to', '');
$img_align = $this->getDataOr('img_align', 'right');


$_helper = $this->helper('dc_catalog/attributeInfo');
$_attr = $this->getAttributeInfo($attribute_code);

$thumbnail_width  = false;
$thumbnail_height = false;

$_imgHtml   = '';
if($_attr) {
	if ($_imgUrl = $_attr->getImageUrl()) {
		$file = Mage::getBaseDir('media') . DS . 'catalog'. DS . 'attribute' . DS . $_attr->getImage();

        $imageInfo = getimagesize($file);
        $width  = $imageInfo[0];
        $height = $imageInfo[1];

		if($img_resize_to) {
			//echo Mage::getBaseUrl('media').$_attr->getImage().'<hr>';
        	$baseDir = Mage::getSingleton('catalog/product_media_config')->getBaseMediaPath();

			$newSizes = explode('x', strtolower($img_resize_to));
			$thumbnail_width  = $newSizes[0];
			$thumbnail_height = isset($newSizes[1]) ? $newSizes[1] : false;

			if($thumbnail_width || $thumbnail_height) {
	        	//keeps aspect ratio for the logo
				if($thumbnail_width == 0) {
					$thumbnail_width = intval($thumbnail_height/$height*$width);
					/*if ($thumbnail_width > $thumbnail_height) {
						$thumbnail_width = $thumbnail_height;
						$thumbnail_height = intval($thumbnail_width/$width*$height);
					}*/
				}
				if($thumbnail_height == 0) {
					$thumbnail_height = intval($thumbnail_width/$width*$height);
					/*if ($thumbnail_height > $thumbnail_width) {
						$thumbnail_height = $thumbnail_width;
						$thumbnail_width = intval($thumbnail_height/$height*$width);
					}*/
				}

				if ($height) $thumbnail_width  = min($thumbnail_width,  intval($width * $thumbnail_height / $height));
				if ($width)  $thumbnail_height = min($thumbnail_height, intval($height * $thumbnail_width / $width));


	        	//resizer looks in /media/catalog/product, our images are in /media/catalog/attribute
	        	//so we go one level above product with ../
		        $_imgUrl = Mage::helper('dc_catalog/image')
		        	->initImage($attribute_code, $_attr->getImage())
		        	->resize($thumbnail_width, $thumbnail_height)
		        	->__toString();
			}
		}

        if ('block' == $img_align) {
			$baseDir = Mage::getSingleton('catalog/product_media_config')->getBaseMediaPath();

			$_imgHtml = '
				<a href="'.$this->getUrl('/').$_attr->getAttributeCode().'/'.$_attr->getIdentifier().'"
				title="'.$this->htmlEscape($_attr->getName()).'"
				style="display: block; background:url(\''.$_imgUrl.'\') no-repeat top center; height: '.($thumbnail_height ? $thumbnail_height : $height).'px"
				</a>';
		} else {
			$_imgHtml = '<img
				width="'.($thumbnail_width ? $thumbnail_width : $width) .'"
		        src="'.$_imgUrl.'"
		        alt="'.$this->htmlEscape($_attr->getValue()).'"
		        title="'.$this->htmlEscape($_attr->getValue()).'"
		        align="'.$img_align.'"
		        class="product-attribute-image" />';
		}
	}
}
/*if ($_imgUrl = $_attr->getImageUrl()) {
	$_imgHtml = '<img
        src="'.$_imgUrl.'"
        alt="'.$this->htmlEscape($_attr->getValue()).'"
        title="'.$this->htmlEscape($_attr->getValue()).'"
        align="'.$img_align.'"
        class="attribute-image" />';
}*/

?>

<?php if($_imgHtml): ?>
	<?php echo $_imgHtml?>
<?php endif; ?>
